"""fixed typo in author model

Revision ID: 63f79ccfdf77
Revises: 8ca8514a4fbc
Create Date: 2023-04-21 18:44:38.916163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f79ccfdf77'
down_revision = '8ca8514a4fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=16), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
